import Header from './components/UI/header/header'
import Footer from './components/UI/footer/footer';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>   
        <Header />
        <main className='h-screen w-full'>{children}</main>
        <Footer />   
      </body>
    </html>
  )
}
